server:
  port: 8081
  jsp-servlet:
    init-parameters:
      development: ture
spring:
  session:
    store-type: redis #  指定使用redis存储session的会话信息
  redis: # 指定redis服务器的相关信息
    host: 192.168.148.134
    port: 6379
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.148.1:3306/ems
    username: root
    password: 123456
  http:
    multipart:
      max-request-size: 209715200
      max-file-size: 209715200
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration: # 开启mybatis的二级缓存
    cache-enabled: true
